---
title: "R Notebook"
---

Read in the necessary libraries.
```{r}
library(sp)
library(GISTools)
library(rgdal)

## create a mini function that makes the date of the detected fire be read in as a POSIXct date, rather than as a character or a string
setClass('yyyymmdd')
setAs("character","yyyymmdd", function(from) as.POSIXct(from, format="%Y%m%d"))

setClass('HHMM')
setAs("character","HHMM", function(from) as.POSIXct(from, format="%H%M"))
```


```{r}
# read in the data. have to have both date and time as character because they need to be combined before being turned into a time object
detections_5km<-read.table("/Users/laurenhendricks/Documents/Borneo/Ketapang_ClimateFire/mcd14ml_KTG_5km.txt",sep=" ",header=T,colClasses = c("character","character","factor","numeric","numeric","numeric","numeric","integer","numeric","integer","factor"))

```





```{r}
# turn it into a spatial points data frame
detections_5km_sp<-SpatialPointsDataFrame(cbind(detections_5km$lon,detections_5km$lat),detections_5km,proj4string = CRS("+proj=longlat +ellps=WGS84"))
                                          
# project the data                                          
detections_5km_sp_proj<-spTransform(detections_5km_sp,"+proj=utm +zone=49 +south +a=6378160 +b=6356774.50408554 +units=m +no_defs")


plot(SEAsia_proj)
plot(detections_5km_sp_proj)
```


Read in a very rough shapefile with the boundaries of the countries, and then extract the three countries that make up Borneo. (We don't need a detailed shapefile here, because it is just to give us a very general idea of where we are and to make sure that things are scaling correctly etc.)
```{r}
# read in the shapefile
countries<-readOGR(dsn="/Users/laurenhendricks/Documents/GIS_Data/ne_110m_admin_0_countries/",layer="ne_110m_admin_0_countries")

## NOTE: if we want better looking (i.e., more accurate) country boundaries, use this shapefile instead (and the rest of the code will still work fine)
#countries<-readOGR(dsn="/Users/laurenhendricks/Documents/GIS_Data/ne_10m_admin_0_map_units/",layer="ne_10m_admin_0_map_units")


# subset out Indonesia, Malaysia, and Brunei
SEAsia<-countries[countries$SOVEREIGNT=="Indonesia"|countries$SOVEREIGNT=="Malaysia"|countries$SOVEREIGNT=="Brunei",]

# plot it to make sure it works properly 
plot(SEAsia)

# reproject it UTM 49 S (CRS from http://spatialreference.org/ref/epsg/23889/)
SEAsia_proj<-spTransform(SEAsia,"+proj=utm +zone=49 +south +a=6378160 +b=6356774.50408554 +units=m +no_defs")

# plot it again to make sure things still look good
plot(SEAsia_proj)
```
